export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_FAILURE = 'AJAX_CALL_FAILURE';

export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSES_FAILURE = 'LOAD_COURSES_FAILURE';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_FAILURE = 'UPDATE_COURSE_FAILURE';

export const CREATE_LOCATION_SUCCESS = 'CREATE_LOCATION_SUCCESS';
export const CREATE_LOCATION_FAILURE = 'CREATE_LOCATION_FAILURE';
export const LOAD_LOCATIONS_SUCCESS = 'LOAD_LOCATIONS_SUCCESS';
export const LOAD_LOCATIONS_FAILURE = 'LOAD_LOCATIONS_FAILURE';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_FAILURE = 'UPDATE_LOCATION_FAILURE';

export const CREATE_HOLE_SUCCESS = 'CREATE_HOLE_SUCCESS';
export const CREATE_HOLE_FAILURE = 'CREATE_HOLE_FAILURE';
export const LOAD_HOLES_SUCCESS = 'LOAD_HOLES_SUCCESS';
export const LOAD_HOLES_FAILURE = 'LOAD_HOLES_FAILURE';
export const UPDATE_HOLE_SUCCESS = 'UPDATE_HOLE_SUCCESS';
export const UPDATE_HOLE_FAILURE = 'UPDATE_HOLE_FAILURE';
